pipeline {
    agent any

    stages {
        stage('Execute Unit Tests in Parallel') {
            parallel {
                stage('Unit Tests - Backend') {
                    agent {
                        docker {
                            image 'snakee/golang-junit:1.21'
                            reuseNode true
                            args '-e HOME=/tmp -e GOCACHE=/tmp/.cache/go-build -e GOPATH=/tmp/go'
                        }
                    }
                    steps {
                        dir('bugtracker-backend') {
                            sh '''
                            go test -v ./... 2>&1 | go-junit-report > test-results.xml

                            # Generate coverage report
                            go test -coverprofile=coverage.out -covermode=atomic ./...
                            go tool cover -html=coverage.out -o coverage.html

                            mkdir -p reports
                            mv coverage.html reports/
                            '''
                        }
                    }
                    post {
                        always {
                            junit 'bugtracker-backend/test-results.xml'
                            publishHTML(target: [
                                reportName: 'Backend Coverage Report',
                                reportDir: 'bugtracker-backend/reports',
                                reportFiles: 'coverage.html',
                                keepAll: true,
                                allowMissing: false,
                                alwaysLinkToLastBuild: true
                            ])
                        }
                    }
                }

                stage('Unit Tests - Frontend') {
                    agent {
                        docker {
                            image 'node:20-alpine'
                            reuseNode true
                            args '-e HOME=/tmp -e NODE_ENV=development'
                        }
                    }
                    steps {
                        dir('bugtracker-frontend') {
                            sh '''
                               npm ci
                               npm test
                               mkdir -p reports
                               mv coverage reports/coverage
                            '''
                        }
                    }
                    post {
                        always {
                            junit 'bugtracker-frontend/test-results.xml'
                            publishHTML(target: [
                                reportName: 'Frontend Coverage Report',
                                reportDir: 'bugtracker-frontend/reports/coverage',
                                reportFiles: 'index.html',
                                keepAll: true,
                                allowMissing: false,
                                alwaysLinkToLastBuild: true
                            ])
                        }
                    }
                }
            }
        }
    }
    post{
        always {
            cleanWs()
        }
    }
}